[versions]
agp = "8.6.0"
kotlin = "1.9.0"
activityKtx = "1.9.0"
appcompat = "1.6.1"
btt = "2.19.6"
bttFork = "fb91b7bd14"
coilCompose = "2.4.0"
glideCompose = "1.0.0-beta01"
composeBom = "2024.05.00"
constraintlayout = "2.1.4"
converterMoshi = "2.9.0"
coreKtx = "1.13.1"
espressoCore = "3.5.1"
fragmentKtx = "1.7.1"
glide = "4.14.2"
gson = "2.10.1"
hiltAndroid = "2.49"
hiltNavigationCompose = "1.2.0"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlinxCoroutinesCore = "1.8.0"
lifecycleLivedataKtx = "2.8.0"
material = "1.12.0"
materialAndroid = "1.6.7"
navigationCompose = "2.8.7"
navigationFragmentKtx = "2.8.7"
navigationUiKtx = "2.8.7"
okhttp3Integration = "4.11.0"
okhttpBom = "4.12.0"
retrofitVersion = "2.9.0"
runtimeLivedata = "1.6.7"
safeArgsKotlin = "2.5.3"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityKtx" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleLivedataKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
btt-android-sdk = { module = "com.github.blue-triangle-tech:btt-android-sdk", version.ref = "btt" }
fork-btt-android-sdk = { module = "com.github.ganesh-aloha:btt-android-sdk", version.ref = "bttFork"}
coil = { module = "io.coil-kt:coil", version.ref = "coilCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glideCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
junit = { module = "junit:junit", version.ref = "junit" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLivedataKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-android = { module = "androidx.compose.material:material-android", version.ref = "materialAndroid" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "okhttp3Integration" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "safeArgsKotlin"}
daggerHiltAndroid = {id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid"}
