package com.bluetriangle.bluetriangledemo

const val SITE_ID = "bluetriangledemo500z"
const val ADD_TO_CART_LIMIT = 3

const val KEY_SITE_ID = "KEY_SITE_ID"
const val KEY_SESSION_ID = "KEY_SESSION_ID"
const val KEY_ANR_ENABLED = "KEY_ANR_ENABLED"
const val KEY_SCREEN_TRACKING_ENABLED = "KEY_SCREEN_TRACKING_ENABLED"
const val KEY_LAUNCH_TEST = "KEY_LAUNCH_TEST"
const val KEY_SHOULD_NOT_SHOW_CONFIGURATION = "KEY_SHOULD_NOT_SHOW_CONFIGURATION"
const val KEY_LAUNCH_SCENARIO = "KEY_LAUNCH_SCENARIO"

const val SCENARIO_APP_CREATE = 1
const val SCENARIO_ACTIVITY_CREATE = 2
const val SCENARIO_ACTIVITY_START = 3
const val SCENARIO_ACTIVITY_RESUME = 4

const val DEFAULT_SITE_ID = "sdkdemo26621z"